// todosReducer
export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

// auth
export const CREATE_USER_INIT = 'CREATE_USER_INIT';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
